### ISSUE TITLE
providing a complete contrib from-source-build

### ISSUE THREAD

**Issue by mwalzer** [OpenMS/dockerfiles#8]
are there any any up- or down-sides to that. Can we briefly discus that here?

**Comment by jpfeuffer** [comment]
I do that in the nightlies. But you will need QT from the pacmans.
If you want to do it, it is fine for me, imho it would not be *necessary* though.

**Comment by jpfeuffer** [comment]
Do you see any advantages? In container size maybe?

**Comment by mwalzer** [comment]
Benefits in container size I guess will be rather minimal, but we *can* shave off some MB.
I think the price to buy a little independence from the resp. OS version library repository is not high. 
But on the other side, we might buy in to more (at first unforeseen) incompatibility issues?

**Comment by hroest** [comment]
I dont see many advantages to using binary contribs. I think that is why we have tests and already now we take most contrib from packages in our tests: https://github.com/OpenMS/OpenMS/blob/develop/.travis.yml#L22

I think in terms of updates and build time there are advantages to using binary contribs, if there is behavior that is different then we have tests for that and we anyways expect our code to work for a range of different versions of the dependencies. If you really want to, here is a recipe for qt + contribs + OpenMS: https://github.com/hroest/docker_files/blob/master/openms/dependencies/manylinux/Dockerfile

**Comment by tapaswenipathak** [comment]
should this be closed?
